version: "3"
services:

  macrobase:
    build: ./macrobase
    hostname: macrobase
    ports:
          - "8080:8080"
          - "88:88/udp"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command: bash -c "{ while ! { pg_isready -h postgres -p 5432; } do sleep 2; done; } && cd /opt/macrobase && python tools/load_demo.py 5432 postgres postgres postgres && bin/frontend.sh && tail -f /dev/null && tail -f /dev/null"]

  postgres:
    image: postgres:10
    hostname: postgres
    environment:
        - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
